insert into public.profiles (
  id,
  username,
  display_name,
  bio,
  avatar_url,
  website_url,
  twitter_url,
  goal,
  verified
)
values
  (
    '11111111-1111-1111-1111-111111111111',
    'pulseforge',
    'Pulse Forge',
    'Building fast AI operators for research teams.',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    'https://pulseforge.ai',
    'https://x.com/pulseforge',
    'Looking for distribution and design partners.',
    true
  ),
  (
    '22222222-2222-2222-2222-222222222222',
    'neuralkit',
    'Neural Kit',
    'Shipping tiny AI tools that remove friction from daily work.',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    'https://neuralkit.dev',
    'https://x.com/neuralkit',
    'Looking for power users and growth feedback.',
    true
  )
on conflict (id) do nothing;

insert into public.apps (
  id,
  creator_id,
  title,
  slug,
  description,
  one_line_hook,
  target_user,
  problem_statement,
  app_url,
  preview_image_url,
  video_demo_url,
  tags,
  category,
  intent_label,
  resources_needed,
  contact_info,
  collaboration_hooks,
  status,
  is_verified,
  version,
  changelog,
  views_count,
  likes_count,
  comments_count,
  saves_count,
  shares_count,
  avg_session_time_seconds,
  bounce_rate,
  time_to_value_seconds,
  health_score
)
values
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    '11111111-1111-1111-1111-111111111111',
    'Prompt Pilot',
    'prompt-pilot',
    'Refine messy prompts into production-ready instructions with context hints and structured outputs.',
    'Turn vague prompts into high-performing instructions in seconds.',
    'AI builders, students, and operators',
    'Most users waste tokens and time iterating on weak prompts.',
    'https://example.com/prompt-pilot',
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    null,
    '["prompting","llm","writing"]'::jsonb,
    'ai_tool',
    'tool',
    'Looking for growth distribution and product feedback.',
    'hello@promptpilot.ai',
    array['distribution','designers']::public.collaboration_need[],
    'active',
    true,
    '1.2.0',
    'Added tone modes and export shortcuts.',
    18420,
    2340,
    128,
    612,
    93,
    41.7,
    0.18,
    1.6,
    91
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    '22222222-2222-2222-2222-222222222222',
    'Agent Sprint',
    'agent-sprint',
    'Run a lightweight browser-based AI operator that drafts task plans, retries failed prompts, and summarizes execution.',
    'A tiny AI operator for daily execution loops.',
    'Founders, students, and operators',
    'People need a fast assistant that helps them move from intent to execution.',
    'https://example.com/agent-sprint',
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    null,
    '["agents","automation","workflow"]'::jsonb,
    'ai_agent',
    'agent',
    'Looking for integration partners and early testers.',
    'team@agentsprint.ai',
    array['developers','funding']::public.collaboration_need[],
    'active',
    true,
    '0.9.1',
    'Improved session recovery and planner latency.',
    12610,
    1710,
    84,
    433,
    52,
    57.2,
    0.14,
    1.9,
    89
  )
on conflict (id) do nothing;
