import Link from "next/link";
import { ArrowRight, ChartColumn, Heart, Save, ShieldCheck, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { getAppBySlug } from "@/lib/mock-data";
import { rankApps } from "@/lib/recommendation";

export default async function AppDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const app = rankApps().find((item) => item.slug === slug) ?? getAppBySlug(slug);
  if (!app) notFound();
  return <main><section className="grid-2"><div className="panel" style={{ background: app.theme.surface }}><div className="row"><span className="kicker"><Sparkles size={14} /> {app.intentLabel}</span>{app.isVerified ? <span className="chip"><ShieldCheck size={14} /> Verified</span> : null}</div><h1 style={{ fontSize: "3rem", marginBottom: "0.75rem" }}>{app.title}</h1><p className="subtitle" style={{ maxWidth: "none" }}>{app.description}</p><div className="row" style={{ marginTop: "1rem" }}>{app.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}</div><div className="row" style={{ marginTop: "1.5rem" }}><Link className="button" href={app.appUrl}>Open runtime <ArrowRight size={16} /></Link><Link className="ghost-button" href="/feed">Back to feed</Link></div></div><div className="grid-2"><div className="stat-card"><div className="muted">Views</div><strong>{app.stats.views.toLocaleString()}</strong></div><div className="stat-card"><div className="muted">Likes</div><strong>{app.stats.likes.toLocaleString()}</strong></div><div className="stat-card"><div className="muted">Saves</div><strong>{app.stats.saves.toLocaleString()}</strong></div><div className="stat-card"><div className="muted">Avg session</div><strong>{app.stats.avgSessionTimeSeconds}s</strong></div></div></section><section className="section-heading"><h2>App details</h2></section><section className="grid-3"><div className="panel"><div className="row"><ChartColumn size={18} /><strong>Health and time to value</strong></div><p className="muted">Health score {app.stats.healthScore} · Time to value {app.stats.timeToValueSeconds}s · Bounce {Math.round(app.stats.bounceRate * 100)}%</p><p>{app.changelog}</p></div><div className="panel"><div className="row"><Heart size={18} /><strong>Who it is for</strong></div><p>{app.whoItsFor}</p><p className="muted">{app.whatItDoes}</p></div><div className="panel"><div className="row"><Save size={18} /><strong>Collaboration hooks</strong></div><div className="row">{app.collaboration.lookingForDevs ? <span className="chip">Looking for devs</span> : null}{app.collaboration.lookingForDesigners ? <span className="chip">Looking for designers</span> : null}{app.collaboration.lookingForFunding ? <span className="chip">Looking for funding</span> : null}</div><p className="muted">{app.resourcesNeeded}</p></div></section></main>;
}
