import Link from "next/link";
import { ArrowRight, BadgeCheck, Flame, Radar, ShieldCheck, Sparkles } from "lucide-react";
import { appConfig } from "@/lib/env";
import { listFeedItems } from "@/lib/server/repository";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const ranked = await listFeedItems();
  return <main><section className="hero"><div className="card hero-card"><span className="kicker"><Sparkles size={14} /> Launch niche: {appConfig.niche}</span><h1 className="title-xl">Frictionless discovery for live web apps.</h1><p className="subtitle">Rupture is now wired as a real full-stack app: persistent records, auth-backed publishing, database-backed feed retrieval, and deployable server routes for Vercel.</p><div className="row" style={{ marginTop: "1.5rem" }}><Link className="button" href="/feed">Explore the live feed <ArrowRight size={16} /></Link><Link className="ghost-button" href="/create">Publish your app</Link></div><div className="grid-3" style={{ marginTop: "2rem" }}><div className="stat-card"><div className="muted">Apps featured</div><strong>{ranked.length}</strong></div><div className="stat-card"><div className="muted">Primary niche</div><strong>AI tools</strong></div><div className="stat-card"><div className="muted">Feed rule</div><strong>&lt; 2s load</strong></div></div></div><div className="grid-2"><div className="card"><div className="row"><ShieldCheck size={18} /><strong>Hard rules</strong></div><ul className="muted"><li>No login walls inside apps</li><li>No broken embeds in accepted inventory</li><li>No slow loads over 2 seconds</li><li>No screenshot-only submissions unless fallback</li></ul></div><div className="card"><div className="row"><Radar size={18} /><strong>Recommendation loop</strong></div><ul className="muted"><li>Session time and stabilize depth</li><li>Semantic similarity from tags and description</li><li>Quality score from bounce, health, and feedback</li><li>Exploration boost for cold start</li></ul></div><div className="card"><div className="row"><BadgeCheck size={18} /><strong>Full-stack creator stack</strong></div><p className="muted">Cookie auth, persistent app records, database feed queries, and real publish endpoints are now in place.</p></div><div className="card"><div className="row"><Flame size={18} /><strong>Top recommendation</strong></div><h3 style={{ marginTop: "0.75rem" }}>{ranked[0]?.title}</h3><p className="muted">{ranked[0]?.hook}</p><Link className="ghost-button" href="/feed">View ranked feed</Link></div></div></section><section><div className="section-heading"><h2>Deployment requirements</h2></div><div className="grid-3"><div className="panel"><h3>DATABASE_URL</h3><p className="muted">Point this at a Postgres database such as Vercel Postgres or Neon.</p></div><div className="panel"><h3>AUTH_SECRET</h3><p className="muted">Used to sign secure session cookies for creator authentication.</p></div><div className="panel"><h3>Seed bootstrap</h3><p className="muted">The app auto-creates tables and demo seed records on first server access.</p></div></div></section><p className="footer-note">Live execution is the product.</p></main>;
}
