import Link from "next/link";
import { ArrowRight, BadgeCheck, Flame, Radar, ShieldCheck, Sparkles } from "lucide-react";
import { APP_NICHE, apps } from "@/lib/mock-data";
import { rankApps } from "@/lib/recommendation";

export default function HomePage() {
  const ranked = rankApps();
  return <main><section className="hero"><div className="card hero-card"><span className="kicker"><Sparkles size={14} /> Launch niche: {APP_NICHE}</span><h1 className="title-xl">Frictionless discovery for live web apps.</h1><p className="subtitle">Rupture is a scrollable feed of interactive apps. Users browse preview mode, tap into stabilized mode, and the ranking engine learns from session depth, app quality, and intent fit.</p><div className="row" style={{ marginTop: "1.5rem" }}><Link className="button" href="/feed">Explore the live feed <ArrowRight size={16} /></Link><Link className="ghost-button" href="/create">Publish your app</Link></div><div className="grid-3" style={{ marginTop: "2rem" }}><div className="stat-card"><div className="muted">Apps featured</div><strong>{apps.length}</strong></div><div className="stat-card"><div className="muted">Primary niche</div><strong>AI tools</strong></div><div className="stat-card"><div className="muted">Feed rule</div><strong>&lt; 2s load</strong></div></div></div><div className="grid-2"><div className="card"><div className="row"><ShieldCheck size={18} /><strong>Hard rules</strong></div><ul className="muted"><li>No login walls inside apps</li><li>No broken embeds in accepted inventory</li><li>No slow loads over 2 seconds</li><li>No screenshot-only submissions unless fallback</li></ul></div><div className="card"><div className="row"><Radar size={18} /><strong>Recommendation loop</strong></div><ul className="muted"><li>Session time and stabilize depth</li><li>Semantic similarity from tags and description</li><li>Quality score from bounce, health, and feedback</li><li>Exploration boost for cold start</li></ul></div><div className="card"><div className="row"><BadgeCheck size={18} /><strong>Creator stack</strong></div><p className="muted">Paste URL, run preflight, add metadata, collaboration hooks, versioning, and publish a live surface.</p></div><div className="card"><div className="row"><Flame size={18} /><strong>Top recommendation</strong></div><h3 style={{ marginTop: "0.75rem" }}>{ranked[0]?.title}</h3><p className="muted">{ranked[0]?.hook}</p><Link className="ghost-button" href="/feed">View ranked feed</Link></div></div></section><section><div className="section-heading"><h2>What ships in this Vercel-ready MVP</h2></div><div className="grid-3">{[["Interactive feed", "Full-screen cards, snap scroll, preview mode, stabilize on tap."],["Creator flow", "URL preflight, required metadata, collaboration hooks, local demo publish."],["App detail surfaces", "Deep-linkable app pages with metrics, lineage-ready metadata, and runtime launch."]].map(([title, copy]) => <div className="panel" key={title}><h3>{title}</h3><p className="muted">{copy}</p></div>)}</div></section><p className="footer-note">Live execution is the product.</p></main>;
}
